class ProjektContentBlocks::BulkWrite::BlockWriter
  ATTRIBUTES = %w[body visible visible_from visible_until margin_bottom].freeze

  attr_reader :projekt

  def initialize(projekt)
    @projekt = projekt
  end

  # Loaded once, before any write, so callers get the blocks as they were
  # when the request arrived.
  def existing_blocks
    @existing_blocks ||=
      SiteCustomization::ContentBlock
        .where(projekt_id: projekt.id)
        .includes(:translations)
        .order(:position)
        .to_a
  end

  def find(item, index)
    content_block = existing_blocks_by_id[item["id"].to_i]

    if content_block.present?
      return content_block
    end

    message =
      if item["id"].present?
        "Content block #{item["id"]} not found for this projekt"
      else
        "id is required"
      end

    raise_invalid(index, [message])
  end

  def create(item, index)
    content_block =
      projekt.content_blocks.build(
        name: "custom",
        locale: SiteCustomization::ContentBlock.canonical_locale,
        key: SiteCustomization::ContentBlock.generate_projekt_key(projekt.id, SecureRandom.hex(4)),
        body: ""
      )

    save(content_block, item, index)
  end

  def update(content_block, item, index)
    save(content_block, item, index)
  end

  # The job of a running AI generation writes to its block when it ends, so
  # the request fails as a whole until the generation is over.
  def destroy_all(content_blocks)
    generating_block = content_blocks.find(&:ai_generation_pending?)

    if generating_block.present?
      raise ProjektContentBlocks::BulkWrite::InvalidRequestError.new(
        "content_blocks" => [
          "Content block #{generating_block.id} is still being generated by AI and cannot be deleted yet"
        ]
      )
    end

    content_blocks.each(&:destroy!)
  end

  def move(content_block, item, index)
    position = item["position"].to_i

    if position < 1
      raise_invalid(index, ["position must be 1 or greater"])
    end

    content_block.insert_at!([position, projekt_blocks.count].min)
  rescue ActiveRecord::RecordInvalid, ActiveRecord::RecordNotSaved
    raise_invalid(index, content_block.errors.full_messages)
  end

  # Pending AI placeholders are hidden by the default scope, so callers never
  # list them. They go after the listed blocks, where a block added at the
  # bottom belongs, and the generation moves the others to their target once
  # it completes.
  def renumber(content_blocks)
    listed_ids = content_blocks.map(&:id)
    placeholder_ids = projekt_blocks.where.not(id: listed_ids).order(:position).pluck(:id)
    ordered_ids = listed_ids + placeholder_ids

    return if ordered_ids.empty?

    projekt_blocks
      .where(id: ordered_ids)
      .update_all(["position = array_position(ARRAY[?]::integer[], id)", ordered_ids])
  end

  private

  def existing_blocks_by_id
    @existing_blocks_by_id ||= existing_blocks.index_by(&:id)
  end

  def projekt_blocks
    SiteCustomization::ContentBlock.unscoped.where(projekt_id: projekt.id)
  end

  def save(content_block, item, index)
    content_block.assign_attributes(attributes_from(item))

    return content_block if content_block.save

    raise_invalid(index, content_block.errors.full_messages)
  end

  # visible is NOT NULL in the database, so a null from the client means
  # "leave it as it is" rather than a value to write.
  def attributes_from(item)
    attributes =
      item
        .slice(*ATTRIBUTES)
        .reject { |attribute, value| attribute == "visible" && value.nil? }

    if attributes.key?("margin_bottom")
      attributes["margin_bottom"] =
        SiteCustomization::ContentBlock.clamp_margin_bottom(attributes["margin_bottom"])
    end

    attributes
  end

  def raise_invalid(index, messages)
    raise ProjektContentBlocks::BulkWrite::InvalidRequestError.new(
      "content_blocks[#{index}]" => messages
    )
  end
end
