class ProjektImports::ExecuteImportJob < ApplicationJob
  queue_as :projekt_imports

  BANNER_ASPECT_RATIO = "16:9".freeze

  def perform(projekt_import_id)
    projekt_import = ProjektImport.find(projekt_import_id)
    # The previous submit attempt's warnings go, the analysis stage's stay: an
    # image the uploaded document does not let us read is still unreadable on the
    # second try, and the admin was told about it before the projekt existed.
    projekt_import.update!(
      status: "submitting",
      warnings: projekt_import.analysis_warnings + unapplied_chat_warnings(projekt_import)
    )

    create_result = ProjektImports::CreateProjektFromImportService.call(projekt_import: projekt_import)
    if !create_result.success?
      projekt_import.mark_failed!(create_result.error, stage: "create_projekt", details: create_result.error_details)
      return
    end

    projekt = create_result.data[:projekt]

    # Content blocks are rendered only now, with the created phases in hand, so
    # links to a participation phase carry its real id and slug. The AI call
    # deliberately runs between the two persistence steps rather than inside
    # either transaction.
    source_images = ProjektImports::AttachSourceImagesService.call(
      projekt_import: projekt_import,
      projekt: projekt
    )

    resolve_result = ProjektImports::ResolveContentBlocksService.call(
      projekt_import: projekt_import,
      phases: create_result.data[:phases],
      image_urls: source_images.data[:image_urls]
    )

    if !resolve_result.success?
      projekt_import.add_warning!(I18n.t("adm.projekts.imports.warnings.content_blocks_unresolved"))
      projekt_import.mark_failed!(
        resolve_result.error,
        stage: "resolve_content_blocks",
        details: (resolve_result.error_details || {}).merge("created_projekt_id" => projekt.id)
      )
      return
    end

    blocks_created = create_content_blocks(projekt_import, projekt)
    return if !blocks_created

    if source_images.data[:hero_attached]
      projekt_import.update!(image_status: "skipped")
    else
      generate_image_if_requested(projekt_import, projekt)
    end

    projekt_import.update!(status: "completed", error_message: nil)
  rescue StandardError => e
    Rails.logger.error("[ProjektImports::ExecuteImportJob] failed: #{e.message}")
    Sentry.capture_exception(e, extra: { projekt_import_id: projekt_import_id, stage: "execute_import_job" }) if defined?(Sentry)
    pi = ProjektImport.find_by(id: projekt_import_id)
    pi&.mark_failed!(e.message, exception: e)
    raise
  end

  private

  # Edits only reach ai_result through the chat's edit tools. A conversation the
  # user contributed to that produced no tool call either predates those tools or
  # is one where the model answered in prose without applying anything — either
  # way the projekt is about to be created from unedited data, so say so.
  #
  # Messages carrying a custom_command are generated by the Summarize and
  # Regenerate buttons rather than typed by the admin. Counting them would warn
  # about dropped changes after a single click on a button that never asks for
  # one.
  #
  # tool_activity is compared in raw SQL on purpose: Rails routes
  # where.not(jsonb_column: []) through ArrayHandler, which yields 1 = 1 and
  # silently matches every row.
  def unapplied_chat_warnings(projekt_import)
    ai_chat = projekt_import.ai_chat
    return [] if ai_chat.blank?

    has_user_message, has_tool_activity = ai_chat.ai_chat_messages.pick(
      Arel.sql(
        "bool_or(role = 'user' AND custom_command IS NULL), " \
        "bool_or(tool_activity <> '[]'::jsonb)"
      )
    )
    return [] if !has_user_message
    return [] if has_tool_activity

    [{
      "message" => I18n.t("adm.projekts.imports.warnings.chat_changes_not_applied"),
      "stage" => ProjektImport::SUBMIT_WARNING_STAGE,
      "at" => Time.current.iso8601
    }]
  end

  # CreateFromImportData writes all blocks in one transaction, so a single
  # invalid block leaves the projekt with none. The projekt itself is already
  # committed by now, so the import is failed while the projekt is kept — the
  # admin can fill the blocks in or delete it.
  def create_content_blocks(projekt_import, projekt)
    ProjektContentBlocks::Services::CreateFromImportData.call(
      projekt: projekt,
      blocks: projekt_import.ai_result["content_blocks"],
      locale: projekt_import.import_locale
    )

    true
  rescue StandardError => e
    Rails.logger.error("[ProjektImports::ExecuteImportJob#create_content_blocks] failed: #{e.message}")
    Sentry.capture_exception(e, extra: { projekt_import_id: projekt_import.id, stage: "create_content_blocks" }) if defined?(Sentry)
    projekt_import.add_warning!(I18n.t("adm.projekts.imports.warnings.content_blocks_unresolved"))
    projekt_import.mark_failed!(
      e.message,
      stage: "create_content_blocks",
      details: { "created_projekt_id" => projekt.id }
    )

    false
  end

  def generate_image_if_requested(projekt_import, projekt)
    if !projekt_import.title_image_generated?
      projekt_import.update!(image_status: "skipped")
      return
    end

    image_prompt = projekt_import.ai_result&.dig("image_prompt")

    if image_prompt.blank?
      projekt_import.update!(image_status: "skipped")
      return
    end

    projekt_import.update!(image_status: "running")

    response = DtApi::Client.new.ai.generate_image(prompt: image_prompt, aspect_ratio: BANNER_ASPECT_RATIO)

    if !response.success?
      projekt_import.update!(image_status: "failed", image_error: "DT image generation failed")
      projekt_import.add_warning!("image_generation: DT returned an error")
      return
    end

    base64 = response.parsed_response["image"]
    if base64.blank?
      projekt_import.update!(image_status: "failed", image_error: "DT returned no image")
      projekt_import.add_warning!("image_generation: DT returned no image")
      return
    end

    attach_image(projekt, base64)
    projekt_import.update!(image_status: "completed")
  rescue StandardError => e
    Rails.logger.error("[ProjektImports::ExecuteImportJob#generate_image] failed: #{e.message}")
    Sentry.capture_exception(e, level: :warning, extra: { projekt_import_id: projekt_import.id, stage: "image_generation" }) if defined?(Sentry)
    projekt_import.update!(image_status: "failed", image_error: e.message)
    projekt_import.add_warning!("image_generation: #{e.message}")
  end

  # Raising on failure is deliberate: generate_image_if_requested rescues it and
  # records image_status "failed". Returning quietly would report a completed
  # image generation that attached nothing.
  def attach_image(projekt, base64)
    result = ::Projekts::AttachPageImageService.call(
      projekt: projekt,
      user: projekt.author,
      data: Base64.decode64(base64),
      filename: "projekt_#{projekt.id}_hero.jpg",
      content_type: "image/jpeg"
    )

    return if result.success?

    raise result.error
  end
end
