class Projekts::Copying::PollCopier < ApplicationService
  # slug is regenerated by Sluggable, budget_id is unique per poll and is
  # rewired by the budget copy, and the ai_stats columns are derived from the
  # source's votes.
  EXCLUDED_POLL_COLUMNS = %w[
    projekt_id projekt_phase_id slug budget_id
    ai_stats ai_stats_refresh_status ai_stats_refreshed_at
  ].freeze

  # Poll::Question#validate_parent_question_id rejects a parent from another
  # poll, so these cannot be carried over and fixed later -- they are left null
  # and resolved by the rewiring pass, which reads them back off the source.
  EXCLUDED_QUESTION_COLUMNS = %w[
    poll_id parent_question_id next_question_id
    contextualize_by_poll_question_id contexted_clone_of_poll_question_id context_id
  ].freeze

  EXCLUDED_ANSWER_COLUMNS = %w[question_id next_question_id].freeze

  def initialize(source_phase:, copy_phase:, record_copier:)
    @source_phase = source_phase
    @copy_phase = copy_phase
    @record_copier = record_copier
  end

  # ProjektPhase::VotingPhase#create_poll already gave the copy an empty poll,
  # so the first source poll takes it over instead of landing beside it.
  def call
    scaffolded_polls = Poll.where(projekt_phase_id: copy_phase.id).order(:id).to_a

    Poll.where(projekt_phase_id: source_phase.id).order(:id).each_with_index do |poll, index|
      copy_poll(poll, scaffolded_polls[index])
    end
  end

  private

    attr_reader :source_phase, :copy_phase, :record_copier

    def copy_poll(source_poll, scaffolded_poll)
      attributes = {
        projekt_phase_id: copy_phase.id,
        projekt_id: copy_phase.projekt_id,
        slug: nil
      }

      copy = record_copier.overwrite_or_copy(
        source_poll, scaffolded_poll,
        attributes: attributes, except: EXCLUDED_POLL_COLUMNS
      )

      replace_scaffolded_image(source_poll, copy)
      record_copier.copy_images(source_poll, copy)
      record_copier.copy_documents(source_poll, copy)
      record_copier.copy_all(source_poll.sdg_relations, attributes: { relatable: copy })

      source_poll.questions.each do |question|
        copy_question(question, copy)
      end
    end

    # VotingPhase#create_poll seeds the scaffolded poll with a copy of the
    # projekt image; the source poll's own image replaces it, since Poll has
    # only one.
    def replace_scaffolded_image(source_poll, copy)
      return if source_poll.image.blank?
      return if copy.image.blank?

      copy.image.destroy!
      copy.reload
    end

    def copy_question(source_question, copy_poll)
      copy = record_copier.build(
        source_question,
        attributes: { poll_id: copy_poll.id },
        except: EXCLUDED_QUESTION_COLUMNS
      )
      copy.votation_type = built_votation_type(source_question)
      record_copier.persist(source_question, copy)

      record_copier.copy_images(source_question, copy)
      record_copier.copy_documents(source_question, copy)

      source_question.question_answers.each do |answer|
        copy_answer(answer, copy)
      end
    end

    # Poll::Question validates votation_type presence, so it has to be in place
    # before the copy is saved.
    def built_votation_type(source_question)
      source_votation_type = source_question.votation_type
      return nil if source_votation_type.blank?

      record_copier.build(
        source_votation_type,
        except: %w[questionable_type questionable_id]
      )
    end

    def copy_answer(source_answer, copy_question)
      copy = record_copier.copy_record(
        source_answer,
        attributes: { question_id: copy_question.id },
        except: EXCLUDED_ANSWER_COLUMNS
      )

      record_copier.copy_images(source_answer, copy)
      record_copier.copy_documents(source_answer, copy)
      record_copier.copy_all(source_answer.videos, attributes: { answer_id: copy.id })
    end
end
