// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import AdmMenuController from "./components/adm_menu_controller"
application.register("adm-menu", AdmMenuController)

import AdmSidebarController from "./adm/sidebar_controller"
application.register("adm-sidebar", AdmSidebarController)

import SortableController from "./sortable_controller"
application.register("sortable", SortableController)

import ComponentsAdmAttributeEditorController from "./components/adm/attribute_editor_controller"
application.register("components-adm-attribute-editor", ComponentsAdmAttributeEditorController)

import ComponentsAdmNewNavbarItemController from "./components/adm/new_navbar_item_controller"
application.register("components-adm-new-navbar-item", ComponentsAdmNewNavbarItemController)

import AdmColorPickerController from "./adm/color_picker_controller"
application.register("adm-color-picker", AdmColorPickerController)

import KernFormCheckFilter from "./kern_form_check_filter_controller"
application.register("kern-form-check-filter", KernFormCheckFilter)

import TableHeaderController from "./components/table/header_controller"
application.register("table-header", TableHeaderController)

import TableActionsController from "./components/table/actions_controller"
application.register("table-actions", TableActionsController)


import ModeSwitcherController from "./mode_switcher_controller"
application.register("mode-switcher", ModeSwitcherController)
