class Projekts::Copying::Serializing::PollSerializer < ApplicationService
  # slug is regenerated by Sluggable and the ai_stats columns are derived from
  # the source's votes. budget_id is unique per poll, so it crosses as a
  # reference and the rewiring pass resolves it.
  EXCLUDED_POLL_COLUMNS = %w[
    slug ai_stats ai_stats_refresh_status ai_stats_refreshed_at
  ].freeze

  # Poll::Question#validate_parent_question_id rejects a parent from another
  # poll, so these five cannot be assigned while the graph is being built --
  # they travel as references and are written in one pass at the end.
  QUESTION_REFERENCES = %w[
    parent_question_id next_question_id contextualize_by_poll_question_id
    contexted_clone_of_poll_question_id context_id
  ].freeze

  def initialize(source_phase:)
    @source_phase = source_phase
  end

  def call
    Poll.where(projekt_phase_id: source_phase.id).order(:id).map do |poll|
      poll_node(poll)
    end
  end

  private

    attr_reader :source_phase

    def poll_node(poll)
      node = Projekts::Copying::Serializing::RecordSerializer.call(
        poll,
        except: EXCLUDED_POLL_COLUMNS,
        references: %w[budget_id]
      )

      node
        .merge(Projekts::Copying::Serializing::AttachableSerializer.call(record: poll))
        .merge(
          "sdg_relations" => Projekts::Copying::Serializing::SdgCodeSerializer.call(source: poll),
          "questions" => poll.questions.map { |question| question_node(question) }
        )
    end

    def question_node(question)
      node = Projekts::Copying::Serializing::RecordSerializer.call(
        question, references: QUESTION_REFERENCES
      )

      node
        .merge(Projekts::Copying::Serializing::AttachableSerializer.call(record: question))
        .merge(
          "votation_type" => votation_type_node(question),
          "answers" => question.question_answers.map { |answer| answer_node(answer) }
        )
    end

    # Poll::Question validates votation_type presence, so the copier has to
    # build one before it saves the question.
    def votation_type_node(question)
      votation_type = question.votation_type
      return nil if votation_type.blank?

      Projekts::Copying::Serializing::RecordSerializer.call(votation_type)
    end

    def answer_node(answer)
      node = Projekts::Copying::Serializing::RecordSerializer.call(
        answer, references: %w[next_question_id]
      )

      node
        .merge(Projekts::Copying::Serializing::AttachableSerializer.call(record: answer))
        .merge("videos" => serialize_all(answer.videos))
    end

    def serialize_all(records)
      records.map { |record| Projekts::Copying::Serializing::RecordSerializer.call(record) }
    end
end
